---
title: "SOC9035 - Análisis Avanzado de Datos II"
format:
  html:
    include-before-body: helpers/remove-nav.html
    include-after-body: helpers/remove-title.html
---

# Presentación

Este curso profundiza en las técnicas de análisis multivariante, permitiendo examinar de manera integrada la interacción de múltiples factores en el estudio de problemas sociales. Se enfatiza la comprensión de los procedimientos y la interpretación rigurosa de los resultados, con un enfoque aplicado mediante el uso de herramientas computacionales, principalmente R y RStudio.

El curso prioriza la aplicación práctica de los métodos estadísticos sin requerir una profundización en sus fundamentos matemáticos. Al finalizar, el estudiante será capaz de analizar datos primarios y secundarios, identificar la técnica estadística adecuada según el contexto y generar informes que comuniquen de manera efectiva los hallazgos obtenidos.

# Objetivos de aprendizaje

Desarrollar la capacidad de aplicar técnicas de estadística multivariante descriptiva e inferencial para analizar datos, formular hipótesis y construir modelos explicativos en investigaciones sociales, asegurando la correcta interpretación y comunicación de los resultados.

## Objetivos de aprendizaje específicos:
1. Gestionar bases de datos complejas, asegurando su preparación y estructuración para el análisis.
2. Definir y estructurar problemas de análisis multivariante, formulando preguntas de investigación con sustento metodológico.
3. Seleccionar técnicas estadísticas adecuadas, justificando su aplicación en función del tipo de datos y los objetivos del análisis.
4. Utilizar herramientas computacionales especializadas, aplicando modelos en R y RStudio de manera efectiva.
5. Interpretar de forma rigurosa los resultados del análisis, identificando sus alcances y limitaciones.
6. Redactar informes técnicos y académicos, comunicando los hallazgos de manera clara, estructurada y fundamentada.

-----------------

**Selecciona el año académico:**

<a href="2026/index.qmd">
    <button class="btn-course">2026</button>
</a>

**Versiones anteriores:**

<a href="https://aadii2025.netlify.app/">
    <button class="btn-course">2025</button>
</a>

<a href="https://aadii2024.netlify.app/">
    <button class="btn-course">2024</button>
</a>

<a href="https://aadii2023.netlify.app/">
    <button class="btn-course">2023</button>
</a>


