---
title: "Práctico 2: Investigación Reproducible y Ciencia Abierta"
subtitle: "Proyectos reproducibles y el protocolo IPO-R"
date: "2026-03-16"
lang: es
format:
  html:
    toc: true
    code-fold: false
    code-tools: true
    df-print: paged
    body-classes: lab-content
---


# 0. Objetivo del Práctico

El objetivo de este práctico es mostrar, de manera sencilla, cómo estructurar un proyecto reproducible en R, integrando análisis de datos, visualización y documentación. Se enfatizan buenas prácticas en el manejo de rutas relativas, modularidad en el código y generación de reportes reproducibles.

# 1. Proyecto de Ejemplo

Este proyecto sigue el protocolo **IPO-R** (Input, Procesamiento, Output), con:
- **Input:** Carpeta que contiene los datos originales.
- **Procesamiento:** Scripts que preparan y analizan la información.
- **Output:** Resultados generados (tablas y gráficos).

Puedes descargar el archivo completo del proyecto en el siguiente enlace:

[Descargar Proyecto Reproducible](IPO-R.zip)

Para revisar un proyecto real de mayor complejidad, utilizando todos los componentes del protocolo, pueden consultar el [ejemplo provisto por LISA](https://lisa-coes.netlify.app/ipo-repro/).

[Descargar ejemplo completo](https://lisa-coes.github.io/ipo/IPO_miniex/IPO_miniex.tar.gz)